orchestrator:
  _target_: p_processes.p01_loading.src.orchestration.loading_orchestrator.LoadingOrchestrator
  engine:
    _target_: p_processes.p01_loading.src.engine.loading_engine.LoadingEngine
    manager:
      _target_: u_utilities.u_io.ResourceManager
  worker:
    _target_: p_processes.p01_loading.src.workers.file_loader.FileLoader
    resolver:
      _target_: u_utilities.u_loading.src.loading_resolver.LoadingResolver
      base_path: data
      dataset_name: census
    sample_size: null
    seed: 42
    data_loader:
      _target_: u_utilities.u_loading.src.loaders.DataLoader
    dcs_loader:
      _target_: u_utilities.u_loading.src.loaders.DCsLoader
    metadata_loader:
      _target_: u_utilities.u_loading.src.loaders.MetadataLoader
    data_encoder:
      _target_: u_utilities.u_loading.src.encoders.DataEncoder
    dcs_encoder:
      _target_: u_utilities.u_loading.src.encoders.DCsEncoder
