_target_: p_processes.p05_evaluating.src.worker.EvaluatingWorker
engine:
  _target_: p_processes.p05_evaluating.src.engine.EvaluatingEngine
  manager:
    _target_: u_utilities.u_io.ResourceManager
core:
  _target_: p_processes.p05_evaluating.src.core.evaluating_core.EvaluatingCore
  evaluators:
    - _target_: p_processes.p05_evaluating.src.evaluators.runtime_evaluator.RuntimeEvaluator
    - _target_: p_processes.p05_evaluating.src.evaluators.deletion_ratio_evaluator.DeletionRatioEvaluator
    - _target_: p_processes.p05_evaluating.src.evaluators.marginals_error_evaluator.MarginalsErrorEvaluator
    - _target_: p_processes.p05_evaluating.src.evaluators.tvd_evaluator.TwoWayTVDEvaluator
    - _target_: p_processes.p05_evaluating.src.evaluators.ml_accuracy_evaluator.MLAccuracyEvaluator
    - _target_: p_processes.p05_evaluating.src.evaluators.violation_evaluator.ViolationEvaluator
    - _target_: p_processes.p05_evaluating.src.evaluators.loss_function_evaluator.LossFunctionEvaluator
    - _target_: p_processes.p05_evaluating.src.evaluators.marginal_generation_evaluator.MarginalGenerationEvaluator
    - _target_: p_processes.p05_evaluating.src.evaluators.marginal_selection_evaluator.MarginalSelectionEvaluator

dataset_name: ???
synthesizer_name: ???
repairer_name: ???
epsilon: ???
seed: ???
size: ???
alpha: ???
experiment_id: ???
timestamp: "v1"
