host: snorlax-login
remote_dir: ~/final_research
python_env: ~/final_research/.venv/bin/python
slurm_defaults:
  partition: ALL
  time: "24:00:00"
  nodes: 1
  ntasks: 1
  cpus_per_task: 8
  mem: 32G
