_target_: p_processes.p04_repairing.src.worker.RepairingWorker
engine:
  _target_: p_processes.p04_repairing.src.engine.RepairingEngine
  manager:
    _target_: u_utilities.u_io.ResourceManager
repairer:
  _target_: p_processes.p04_repairing.p04b_classic_repairing.src.core.classic_vc_repairer.ClassicVCRepairer
  alpha: 0.5

dataset_name: ???
synthesizer_name: ???
repairer_name: "classic_vc"
epsilon: ???
seed: ???
size: ???
noise_level: ???
alpha: 0.5
