experiment_name: experiment_8_repair_comparison
loader:
  _target_: s06_analysis.src.io.result_loader.ResultLoader
generator:
  _target_: s06_analysis.src.io.notebook_generator.NotebookGenerator
flattener:
  _target_: s06_analysis.src.io.result_flattener.ResultFlattener
output_dir: notebooks
