_target_: s03_marginals.src.components.top_k_obtainer.TopKObtainer
selection_budget: 0.5
generation_budget: 0.5
k: 20
seed: 42
utility_function:
  _target_: s03_marginals.src.components.utility_functions.distance_utility.DistanceUtility
