_target_: p_processes.p03_marginals.src.worker.MarginalsWorker
engine:
  _target_: p_processes.p03_marginals.src.engine.MarginalsEngine
  manager:
    _target_: u_utilities.u_io.ResourceManager
core:
  _target_: p_processes.p03_marginals.src.core.marginals_core.MarginalsCore

dataset_name: ???
experiment_name: ${dataset_name}
noise_level: 0.0
