_target_: p_processes.p03_marginals.src.worker.MarginalsWorker
engine:
  _target_: p_processes.p03_marginals.src.engine.MarginalsEngine
  manager:
    _target_: u_utilities.u_io.ResourceManager
core:
  _target_: p_processes.p03_marginals.src.core.marginals_core.MarginalsCore
  obtainer:
    _target_: p_processes.p03_marginals.src.TopKObtainer
    experiment_name: ${experiment_name}
    dataset_name: ${dataset_name}
    selection_budget: 0.5
    generation_budget: 0.5
    k: 20
    seed: 42
    exclude_dc_attrs: False
    force_target_attr: True
    utility_function:
      _target_: p_processes.p03_marginals.src.DistanceUtility

dataset_name: ???
experiment_name: ${dataset_name}
