_target_: s01_loading.src.components.file_loader.FileLoader
name: adult
base_path: data
size: null
seed: 42
data_loader:
  _target_: s01_loading.src.components.data_loader.DataLoader
dcs_loader:
  _target_: s01_loading.src.components.dcs_loader.DCsLoader
metadata_loader:
  _target_: s01_loading.src.components.metadata_loader.MetadataLoader
data_encoder:
  _target_: s01_loading.src.components.data_encoder.DataEncoder
dcs_encoder:
  _target_: s01_loading.src.components.dcs_encoder.DCsEncoder
