_target_: s01_loading.src.io.FileLoader
name: compas
base_path: data
size: null
seed: 42
data_loader:
  _target_: s01_loading.src.loaders.DataLoader
dcs_loader:
  _target_: s01_loading.src.loaders.DCsLoader
metadata_loader:
  _target_: s01_loading.src.loaders.MetadataLoader
data_encoder:
  _target_: s01_loading.src.encoders.DataEncoder
dcs_encoder:
  _target_: s01_loading.src.encoders.DCsEncoder
