# %%
# [MARKDOWN]
# # Experiment 7 Analysis
# Automated analysis generated by Stage 06.

# %%
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path
import sys

# Ensure we can import from s06_analysis
sys.path.append(str(Path.cwd().parent.parent))
from s06_analysis.src.io.result_flattener import ResultFlattener

# Configure seaborn styling
sns.set_theme(style="whitegrid")

# Load flattened data
DATA_PATH = Path("../input/flattened_results.csv")
raw_df = pd.read_csv(DATA_PATH)
flattener = ResultFlattener()
df, topology_df = flattener.flatten(raw_df)

print(f"Loaded {len(df)} records.")
df.head()

# %%
# [MARKDOWN]
# ## 1. Deletion Ratio by Dataset
# Analyzes the deletion ratio using repair algorithm as hue and synthesizer as style.

# %%
g = sns.FacetGrid(df, col="dataset", sharey=False, height=5, aspect=1.2)
g.map_dataframe(sns.lineplot, x="epsilon", y="deletion_ratio", hue="repair_algorithm", style="synthesizer", markers=True, markersize=8)
g.add_legend()
g.set_axis_labels("Epsilon (Privacy Budget)", "Deletion Ratio")
g.fig.suptitle("Deletion Ratio vs Epsilon", y=1.05)
plt.show()

# %%
# [MARKDOWN]
# ## 2. Marginals Error

# %%
g = sns.FacetGrid(df, col="dataset", sharey=False, height=5, aspect=1.2)
g.map_dataframe(sns.lineplot, x="epsilon", y="marginals_error_repaired", hue="repair_algorithm", style="synthesizer", markers=True, markersize=8)
g.add_legend()
g.set_axis_labels("Epsilon", "Marginals Error")
g.fig.suptitle("Marginals Error vs Epsilon", y=1.05)
plt.show()

# %%
# [MARKDOWN]
# ## 3. Marginals Loss

# %%
g = sns.FacetGrid(df, col="dataset", sharey=False, height=5, aspect=1.2)
g.map_dataframe(sns.lineplot, x="epsilon", y="loss_marginal_repaired", hue="repair_algorithm", style="synthesizer", markers=True, markersize=8)
g.add_legend()
g.set_axis_labels("Epsilon", "Marginals Loss")
g.fig.suptitle("Marginals Loss vs Epsilon", y=1.05)
plt.show()

# %%
# [MARKDOWN]
# ## 4. Total Variation Distance (TVD)

# %%
g = sns.FacetGrid(df, col="dataset", sharey=False, height=5, aspect=1.2)
g.map_dataframe(sns.lineplot, x="epsilon", y="tvd_repaired", hue="repair_algorithm", style="synthesizer", markers=True, markersize=8)
g.add_legend()
g.set_axis_labels("Epsilon", "Total Variation Distance (TVD)")
g.fig.suptitle("TVD vs Epsilon", y=1.05)
plt.show()

# %%
# [MARKDOWN]
# ## 5. Machine Learning Accuracy

# %%
g = sns.FacetGrid(df, col="dataset", sharey=False, height=5, aspect=1.2)
g.map_dataframe(sns.lineplot, x="epsilon", y="ml_acc_repaired", hue="repair_algorithm", style="synthesizer", markers=True, markersize=8)
g.add_legend()
g.set_axis_labels("Epsilon", "ML Accuracy")
g.fig.suptitle("ML Accuracy vs Epsilon", y=1.05)
plt.show()

# %%
# [MARKDOWN]
# ## 6. Runtime

# %%
g = sns.FacetGrid(df, col="dataset", sharey=False, height=5, aspect=1.2)
g.map_dataframe(sns.lineplot, x="epsilon", y="repair_runtime", hue="repair_algorithm", style="synthesizer", markers=True, markersize=8)
g.add_legend()
g.set_axis_labels("Epsilon", "Runtime (seconds)")
g.fig.suptitle("Runtime vs Epsilon", y=1.05)
plt.show()
